### ISSUE TITLE
no task after 2020

### ISSUE THREAD

**Issue by lullcant** [potamides/arxiv-latex-extract#2]
I want to crawl the data after 2021 from arxiv and I set  the cut off as follow.
 cutoff = datetime(2020, 1, 1) # tikz 1.0 release date
And I found that no data can be downloaded.
Is the resource up to date, how can I get the latest data from arxiv. Thanks

**Comment by potamides** [comment]
Did you install boto3 and set up your AWS credentials (cf. the README.md)? The arxiv bulk data mirror on archive.org is a bit out of date and only goes up until the end of 2020, unfortunately.

**Comment by lullcant** [comment]
Thanks，it works after I install boto3 and set up the AWS credentials
